// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ticwxzgdbwvjbtnyqrop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpY3d4emdkYnd2amJ0bnlxcm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTA2ODYsImV4cCI6MjA3MjY4NjY4Nn0.Wg3mldv0t8sI4_OhYHvs82oRopmQshKo4FavS9pFiiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});